name: PKGBUILD Test CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yml'
      - 'action.yml'
      - 'entrypoint.sh'
      - 'base/Dockerfile'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'action.yml'
      - 'entrypoint.sh'
  workflow_dispatch:

concurrency:
  group: ci-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  waiter:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    name: Test base image rebuild

    steps:

      - uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 2

      - name: Wait for base rebuild
        if: ${{ github.event_name == 'push' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff --quiet HEAD^ HEAD -- base/Dockerfile; then
            echo "Base Dockerfile changed. Waiting for base build workflow to complete..."
            sleep 5s
            RUN_ID=$(gh run list --workflow "base.yml" --commit ${{ github.sha }} --json databaseId --jq '.[0].databaseId')
            if [ -z "$RUN_ID" ] || [ "$RUN_ID" == "null" ]; then
              echo "Error: Could not find a run for base.yml with commit ${{ github.sha }}"
              exit 1
            fi
            gh run watch "$RUN_ID" --exit-status
            echo "Base rebuild completed succesfully!"
          fi

  test:
    runs-on: ubuntu-latest
    needs: [waiter]
    permissions:
      actions: read
      contents: read
    name: Test Builds

    strategy:
      matrix:
        include:
          - pkg-name: zig-bin
          - pkg-name: libdovi-git
          - pkg-name: libhdr10plus-rs-git
          - pkg-name: x265-git
            run: 'x265 -V'
          - pkg-name: x265-pmod-git
          - pkg-name: aom-psy101-git
          - pkg-name: aom-git
            run: 'aomenc --help'
          - pkg-name: llvm-bolt
          - pkg-name: onnxruntime-cpu
          - pkg-name: vapoursynth-plugin-mlrt-ort-cpu-runtime-git
          - pkg-name: zlib-ng-compat-git
      fail-fast: false

    steps:

      - uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 2
          path: action

      - uses: actions/checkout@v7
        with:
          repository: rokibhasansagar/Arch_PKGBUILDs
          ref: main
          path: Arch_PKGBUILDs

      - name: aom-git preparation
        if: ${{ matrix.pkg-name == 'aom-git' }}
        run: |
          cd Arch_PKGBUILDs/TEST/
          mv aom* ../
          cd ..

      - name: pkgbuild
        uses: ./action
        with:
          target: pkgbuild
          debug: true
          pkgname: Arch_PKGBUILDs/${{ matrix.pkg-name }}

      - name: srcinfo
        continue-on-error: true
        uses: ./action
        with:
          target: srcinfo
          pkgname: Arch_PKGBUILDs/${{ matrix.pkg-name }}

      - name: run
        if: ${{ matrix.run != '' }}
        continue-on-error: true
        uses: ./action
        with:
          target: run
          pkgname: Arch_PKGBUILDs/${{ matrix.pkg-name }}
          command: ${{ matrix.run }}

